// GENERATED from src/features/awards/announcement.ts (awardAnnouncement over every tier of
// every track in tracks.ts). Do not edit by hand: run
//   UPDATE_AWARD_PUSH_COPY=1 npx jest src/features/awards/award-push-copy.test.ts
// and award-push-copy.test.ts fails whenever this file and the app disagree.

/** What an earned tier is called, and what was done to earn it, keyed `award:tier`. */
export const AWARD_COPY: Readonly<
  Record<string, { readonly title: string; readonly achievement: string | null }>
> = {
  "movie-muncher:bronze": { title: "Movie Muncher", achievement: "Watched 50 movies" },
  "movie-muncher:silver": { title: "Movie Muncher", achievement: "Watched 200 movies" },
  "movie-muncher:gold": { title: "Movie Muncher", achievement: "Watched 1,000 movies" },
  "season-snacker:bronze": { title: "Season Snacker", achievement: "Watched 15 TV seasons" },
  "season-snacker:silver": { title: "Season Snacker", achievement: "Watched 60 TV seasons" },
  "season-snacker:gold": { title: "Season Snacker", achievement: "Watched 250 TV seasons" },
  "invite-instigator:bronze": { title: "Invite Instigator", achievement: "Brought 3 people to bingd" },
  "invite-instigator:silver": { title: "Invite Instigator", achievement: "Brought 15 people to bingd" },
  "invite-instigator:gold": { title: "Invite Instigator", achievement: "Brought 50 people to bingd" },
  "queue-dragon:seedling": { title: "Seedling", achievement: "Kept 25 titles on your watchlist" },
  "queue-dragon:hoarder": { title: "Hoarder", achievement: "Kept 100 titles on your watchlist" },
  "queue-dragon:queue-dragon": { title: "Queue Dragon", achievement: "Kept 300 titles on your watchlist" },
  "rating-rascal:scribbler": { title: "Scribbler", achievement: "Ranked 100 titles" },
  "rating-rascal:score-goblin": { title: "Score Goblin", achievement: "Ranked 500 titles" },
  "rating-rascal:rank-beast": { title: "Rank Beast", achievement: "Ranked 2,000 titles" },
  "comment-gremlin:whisper": { title: "Whisper", achievement: "Wrote 20 comments" },
  "comment-gremlin:chatterbox": { title: "Chatterbox", achievement: "Wrote 100 comments" },
  "comment-gremlin:megaphone": { title: "Megaphone", achievement: "Wrote 500 comments" },
  "hype-courier:nudge": { title: "Nudge", achievement: "Sent 25 recommendations" },
  "hype-courier:messenger": { title: "Messenger", achievement: "Sent 100 recommendations" },
  "hype-courier:hype-train": { title: "Hype Train", achievement: "Sent 500 recommendations" },
  "scream-snack:spooky-sip": { title: "Spooky Sip", achievement: "Watched 25 horror titles" },
  "scream-snack:slash-snack": { title: "Slash Snack", achievement: "Watched 100 horror titles" },
  "scream-snack:nightmare-fuel": { title: "Nightmare Fuel", achievement: "Watched 300 horror titles" },
  "lol-mode:giggle": { title: "Giggle", achievement: "Watched 25 comedies" },
  "lol-mode:cackle": { title: "Cackle", achievement: "Watched 100 comedies" },
  "lol-mode:wheeze": { title: "Wheeze", achievement: "Watched 300 comedies" },
  "softie-hours:sniffle": { title: "Sniffle", achievement: "Watched 25 drama or romance titles" },
  "softie-hours:tearjerker": { title: "Tearjerker", achievement: "Watched 100 drama or romance titles" },
  "softie-hours:sob-lord": { title: "Sob Lord", achievement: "Watched 300 drama or romance titles" },
  "space-brain:liftoff": { title: "Liftoff", achievement: "Watched 25 science fiction titles" },
  "space-brain:moonwalker": { title: "Moonwalker", achievement: "Watched 100 science fiction titles" },
  "space-brain:galaxy-mind": { title: "Galaxy Mind", achievement: "Watched 300 science fiction titles" },
  "boom-club:spark": { title: "Spark", achievement: "Watched 25 action titles" },
  "boom-club:blast": { title: "Blast", achievement: "Watched 100 action titles" },
  "boom-club:detonation": { title: "Detonation", achievement: "Watched 300 action titles" },
  "toon-bloom:sketch": { title: "Sketch", achievement: "Watched 20 animated titles" },
  "toon-bloom:ink-pop": { title: "Ink Pop", achievement: "Watched 75 animated titles" },
  "toon-bloom:cartoon-chaos": { title: "Cartoon Chaos", achievement: "Watched 250 animated titles" },
  "truth-worm:curious": { title: "Curious", achievement: "Watched 15 documentaries" },
  "truth-worm:investigator": { title: "Investigator", achievement: "Watched 50 documentaries" },
  "truth-worm:deep-dive": { title: "Deep Dive", achievement: "Watched 150 documentaries" },
  "passport-mode:hitchhiker": { title: "Hitchhiker", achievement: "Watched 15 non-English titles" },
  "passport-mode:jetsetter": { title: "Jetsetter", achievement: "Watched 75 non-English titles" },
  "passport-mode:globetrotter": { title: "Globetrotter", achievement: "Watched 250 non-English titles" },
  "time-hopper:retro-snack": { title: "Retro Snack", achievement: "Watched 25 titles released before 2000" },
  "time-hopper:vhs-vibes": { title: "VHS Vibes", achievement: "Watched 100 titles released before 2000" },
  "time-hopper:time-traveler": { title: "Time Traveler", achievement: "Watched 300 titles released before 2000" },
  "genre-gremlin:dabbler": { title: "Dabbler", achievement: "Watched 14 different genres" },
  "genre-gremlin:mixer": { title: "Mixer", achievement: "Watched 16 different genres" },
  "genre-gremlin:chaos-collector": { title: "Chaos Collector", achievement: "Watched 17 different genres" },
  "two-screen-life:tourist": { title: "Tourist", achievement: "Watched 15 movies and 15 TV seasons" },
  "two-screen-life:resident": { title: "Resident", achievement: "Watched 50 movies and 50 TV seasons" },
  "two-screen-life:mayor": { title: "Mayor", achievement: "Watched 150 movies and 150 TV seasons" },
  "heart-magnet:warmup": { title: "Warmup", achievement: "Got 50 reactions on your activity" },
  "heart-magnet:favorite": { title: "Favorite", achievement: "Got 250 reactions on your activity" },
  "heart-magnet:scene-stealer": { title: "Scene Stealer", achievement: "Got 1,000 reactions on your activity" },
  "mutual-mania:hello": { title: "Hello", achievement: "Followed 5 people who follow you back" },
  "mutual-mania:inner-circle": { title: "Inner Circle", achievement: "Followed 25 people who follow you back" },
  "mutual-mania:main-character": { title: "Main Character", achievement: "Followed 100 people who follow you back" },
};
